### ISSUE TITLE
Arrow.setEnd() only moves arrow head, not whole arrow

### ISSUE THREAD

**Issue by lucadavies** [finneyj/GameArena#11] opened 2018-05-22 20:44 UTC
Calling Arrow.setEnd doesn't move the neck of the arrow.

`private void moveArrow(char d) //d is input (left/right/none hence init)`

    {
        double endX = arrow.getEndX();
        double endY = arrow.getEndY();
        double startX = balls.get(0).getXPosition();
        double startY = balls.get(0).getYPosition() - ballSize;
        //arrow.removeArrow(game);
        if (d == 'L')
        {
            //arrow = new Arrow(startX, startY, endX - 1, endY, 5, "WHITE", game);
            arrow.setEnd(endX - 1, endY); //<---- doesn't work
        }
        else if (d == 'R')
        {
            //arrow = new Arrow(startX, startY, endX + 1, endY, 5, "WHITE", game);
            arrow.setEnd(endX + 1, endY); //<---- doesn't work
        }
        else if (d == 'x') //staring position
        {
            arrow = new Arrow(startX, startY, startX, startY - 30, 5, "WHITE", game);
        }
    }

**Comment by finneyj** [comment] 2018-05-23 08:35
Ta. Now fixed in master with commit: https://github.com/finneyj/GameArena/commit/9bb9fffa5d4db258bfcdc5b206cfc58256470182

Please reopen this issue if the problem isn't fixed for you.

**Closed by finneyj** 2018-05-23 08:35 UTC
